name: nexus_backend
version: 0.1.0
publish_to: none

environment:
  sdk: ^3.2.1

dependencies:
  args: ^2.5.0
  crypto: ^3.0.6
  dotenv: ^4.2.0
  eloquent: ^3.4.3
  get_it: ^8.0.3
  jose: ^0.3.5
  logging: ^1.3.0
  redis: ^4.1.0
  shelf: ^1.4.1
  shelf_cors_headers: ^0.1.5
  shelf_router: ^1.1.4
  nexus_core:
    path: ../core
  essential_core:
    path: ../packages/essential_core

dev_dependencies:
  lints: ^5.0.0
  shelf_test_handler: ^2.0.2
  test: ^1.26.3