name: limitless_ui
description: Reusable AngularDart UI components and directives for web applications.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.2.1

dependencies:
  essential_core:
    path: ../essential_core
  popper:
    path: ../popper  
  collection: ^1.19.1
  intl: any
  ngdart: 8.0.0-dev.4
  ngforms: 5.0.0-dev.3
  ngrouter: 4.0.0-dev.3

  sass_builder: ^2.2.1

dev_dependencies:
  lints: ^5.0.0

